apiVersion: constraints.gatekeeper.sh/v1beta1
kind: KunervaAdmission
metadata:
  name: paymentservice
spec:
  match:
    kinds:
    - apiGroups: ["cilium.io"]
      kinds: ["CiliumNetworkPolicy"]
  parameters:
    matchLabels:
      app: paymentservice
    toPorts:
    - ports:
      - port: "50051"
        protocol: TCP

